In [8]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digit=load_digits()

In [9]:
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,test_size=0.3)

In [10]:
# lr=LogisticRegression()
# lr.fit(x_train,y_train)
# lr.score(x_test,y_test)

C:\Users\shris\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9481481481481482

In [11]:
# svm=SVC()
# svm.fit(x_train,y_train)
# svm.score(x_test,y_test)

0.9907407407407407

In [13]:
# rf=RandomForestClassifier(n_estimators=40)
# rf.fit(x_train,y_train)
# rf.score(x_test,y_test)

0.975925925925926

In [14]:
def get_Score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [23]:
get_Score(LogisticRegression(max_iter=10000),x_train,x_test,y_train,y_test)

0.9462962962962963

In [24]:
get_Score(svm,x_train,x_test,y_train,y_test)

0.9907407407407407

In [25]:
get_Score(rf,x_train,x_test,y_train,y_test)

0.9722222222222222

In [26]:
from sklearn.model_selection  import KFold

In [28]:
kf=KFold(n_splits=3)

In [29]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [30]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)

In [35]:
scores_lr=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digit.data):
    x_train,x_test,y_train,y_test=digit.data[train_index],digit.data[test_index],\
                                  digit.target[train_index],digit.target[test_index]  
    scores_lr.append(get_Score(LogisticRegression(max_iter=10000),x_train,x_test,y_train,y_test))
    scores_svm.append(get_Score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_Score(RandomForestClassifier(),x_train,x_test,y_train,y_test))


In [36]:
scores_lr

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [37]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [38]:
scores_rf

[0.9365609348914858, 0.9482470784641068, 0.9232053422370617]

In [43]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=10000),digit.data,digit.target)

array([0.925     , 0.87777778, 0.93871866, 0.93593315, 0.89693593])