In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

iris=load_iris()


In [7]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [13]:
lr_scores=cross_val_score(LogisticRegression(max_iter=10000),iris.data,iris.target)
lr_scores


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
np.average(lr_scores)

0.9733333333333334

In [14]:
svc_scores=cross_val_score(SVC(),iris.data,iris.target)
svc_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [17]:
np.average(svc_scores)

0.9666666666666666

In [15]:
rf_Scores=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf_Scores

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [18]:
np.average(rf_Scores)

0.9533333333333334