# not gradient descent
##saving model

In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [6]:
df=pd.read_csv('area vs prices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [8]:
model.fit(df[['area']],df.price)

LinearRegression()

In [9]:
model.predict([[3400]])

array([642294.52054795])

In [10]:
import pickle

In [11]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [13]:
with open('model_pickle','rb')as f:
   mp = pickle.load(f)

In [14]:
mp.predict([[5000]])

array([859554.79452055])

In [15]:
import joblib

In [16]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [17]:
mj=joblib.load('model_joblib')


In [18]:
mj.predict([[5000]])

array([859554.79452055])